[project]
name = "datagouvpy"
version = "0.1.0"
description = "A Python client for the data.gouv.fr API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.16",
    "async-timeout>=5.0.1",
    "pandas>=2.2.3",
]
